### ISSUE TITLE
Active Model Serializers 0.10.0 no root method

### ISSUE THREAD

**Issue by Janther** [netguru/devise-ios-rails#21]
The latest version of Active Model Serializer throws a no root method exception which breaks on `app/serializers/errors_serializer.rb` second line

**Comment by jm90m** [comment]
I was stuck on this issue for a bit. When I tried to run my rails server on heroku it would pop up with:

```/app/vendor/bundle/ruby/2.2.0/gems/devise-ios-rails-1.0.2/app/serializers/errors_serializer.rb:2:in `<class:ErrorsSerializer>': undefined method `root' for ErrorsSerializer:Class (NoMethodError)
	from /app/vendor/bundle/ruby/2.2.0/gems/devise-ios-rails-1.0.2/app/serializers/errors_serializer.rb:1:in `<top (required)>'```

Solved it by using an earlier version of active model serializer :/.

I added this to my Gemfile: `gem 'active_model_serializers', '~> 0.9.0'`
